### ISSUE TITLE
Default Settings

### ISSUE THREAD

**Issue by bryceadams** [tommcfarlin/WordPress-Settings-Sandbox#3]
Hey Tom,

Regarding setting defaults for settings, what do you feel is the best way? I ended up using something like this (with the Settings Sandbox):

``` php
function namespace_option( $key ) {

    $namespace_options = get_option( 'namespace_options' );

     /* Define the array of defaults */ 
    $defaults = array(
        'option_1'     => 1,
        'option_2'     => 0,
        'option_3'    => 'fade'
    );

    $namespace_options = wp_parse_args( $namespace_options, $defaults );

    if( isset($namespace_options[$key]) )
         return $namespace_options[$key];

    return false;
}
```

So then I'd use `<?php echo namespace_option( 'option_1' ); ?>` to output an option's value.

**Any preferred/better way?**

**Comment by tommcfarlin** [comment]
Here's how I normally do it. Note that I'm using the following things:
- 'Example' is the name of the theme, so I'm prefixing each of my functions with `example`
- The text is localized and the localization domain is `example`
- Note the validation function referenced in `example_setup_theme_presentation_options` is not defined in this comment (it should be clear enough from the rest of the code in this repository ;).

First, I write a function that initializes a section and its options. For example, say we're working with presentation options that's going to include a `fav_icon` and a `layout.`

This function is hooked into [admin_init](http://codex.wordpress.org/Plugin_API/Action_Reference/admin_init).

``` php
function example_setup_theme_presentation_options() {

    // If the layout options don't exist, create them.
    if( false == get_option( 'example_theme_presentation_options' ) ) { 
        add_option( 'example_theme_presentation_options', apply_filters( 'example_theme_presentation_options', get_example_theme_default_presentation_options() ) );
    } // end if

    // Presentation options (composed of layout and content)
    add_settings_section(
        'presentation',
        '',
        'example_theme_presentation_options_display',
        'example_theme_presentation_options'
    );

    add_settings_section(
        'layout',
        __( 'Layout and Design', 'example' ),
        'example_theme_layout_options_display',
        'example_theme_presentation_options'
    );

    add_settings_field(
        'fav_icon',
        __( 'Site Icon', 'example' ),
        'fav_icon_display',
        'example_theme_presentation_options',
        'layout'
    );

    register_setting(
        'example_theme_presentation_options',
        'example_theme_presentation_options',
        'example_theme_presentation_options_validate'
    );

} // end example_setup_theme_presentation_options
add_action( 'admin_init', 'example_setup_theme_presentation_options' );
```

Then, I define a function that's used to initialize the default options for a given set of options. Since I'm working with presentation options.

Notice that this function is called in the function above in the call to `add_option.` Separating them makes it really easy to:
- Add new fields to the settings section in the previous function
- Initialize default values in the following function

``` php
function get_example_default_presentation_options() {

    $defaults = array(
        'fav_icon'                  =>  '',
        'layout'                    =>  'right_sidebar_layout',
    );

    return apply_filters ( 'example_default_presentation_options', $defaults );

} // end get_example_default_presentation_options
```

Note the use of [apply_filters](http://codex.wordpress.org/Function_Reference/apply_filters).

Hopefully this helps!
